run_mode: 'finetune'

model:
  model_config:
    type: LlamaConfig
    batch_size: 1 # add for increase predict
    hidden_size: 3584
    num_layers: 28
    num_heads: 28
    n_kv_heads: 4
    vocab_size: 152064
    intermediate_size: 18944
    qkv_has_bias: True
    rms_norm_eps: 1.0e-6
    theta: 1000000.0
    max_position_embedding: 131072
    emb_dropout_prob: 0.0
    eos_token_id: 151643
    pad_token_id: 151643
    compute_dtype: "bfloat16"
    layernorm_compute_type: "float32"
    softmax_compute_type: "float16"
    rotary_dtype: "float32"
    param_init_type: "float32"
    use_past: False
    extend_method: "None" # support "None", "PI", "NTK"
    use_flash_attention: True
    fine_grain_interleave: 1
    qkv_concat: False
    block_size: 32
    num_blocks: 128
    offset: 0
    checkpoint_name_or_path: ""
    repetition_penalty: 1
    max_decode_length: 512
    top_k: 0
    top_p: 0.8
    do_sample: False
    compute_in_2d: True
    # configuration items copied from Qwen
    rotary_pct: 1.0
    rotary_emb_base: 1000000
    kv_channels: 128

  arch:
    type: LlamaForCausalLM

processor:
  return_tensors: ms
  tokenizer:
    model_max_length: 32768
    vocab_file: ""
    merges_file: ""
    unk_token: "<|endoftext|>"
    eos_token: "<|endoftext|>"
    pad_token: "<|endoftext|>"
    type: Qwen2Tokenizer
  type: Qwen2Processor
